# Generated by Django 6.1.2 on 2026-10-07 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpn', models.CharField(help_text='Manufacturer Part Number', max_length=100, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('msrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(default='CPU', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CpuSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(max_length=20)),
                ('core_count', models.IntegerField()),
                ('thread_count', models.IntegerField()),
                ('base_clock_ghz', models.FloatField()),
                ('boost_clock_ghz', models.FloatField()),
                ('tdp_watts', models.IntegerField(help_text='Power consumption in watts')),
                ('has_integrated_gpu', models.BooleanField(default=False)),
                ('included_cooler', models.BooleanField(default=False)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_spec', to='components.component')),
            ],
        ),
    ]
