# Generated by Django 6.1.2 on 2026-10-07 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotherboardSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(help_text='e.g., AM5, LGA1700', max_length=20)),
                ('form_factor', models.CharField(help_text='e.g., ATX, Micro ATX, Mini ITX', max_length=20)),
                ('memory_type', models.CharField(help_text='e.g., DDR4, DDR5', max_length=10)),
                ('memory_slots', models.IntegerField()),
                ('max_memory_gb', models.IntegerField()),
                ('has_wifi', models.BooleanField(default=False)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard_spec', to='components.component')),
            ],
        ),
    ]
