# Generated by Django 6.1.2 on 2026-10-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_motherboardspec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
            ],
            options={
                'verbose_name': 'CPU',
                'verbose_name_plural': 'CPUs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('components.component',),
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
            ],
            options={
                'verbose_name': 'Motherboard',
                'verbose_name_plural': 'Motherboards',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('components.component',),
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Component', 'verbose_name_plural': 'All Components'},
        ),
        migrations.AddField(
            model_name='motherboardspec',
            name='chipset',
            field=models.CharField(default='', help_text='e.g., B650, Z790, X670E', max_length=50),
        ),
        migrations.AddField(
            model_name='motherboardspec',
            name='m2_slots',
            field=models.IntegerField(default=0, help_text='Number of M.2 NVMe slots'),
        ),
        migrations.AddField(
            model_name='motherboardspec',
            name='sata_slots',
            field=models.IntegerField(default=0, help_text='Number of SATA ports'),
        ),
        migrations.AlterField(
            model_name='cpuspec',
            name='tdp_watts',
            field=models.IntegerField(),
        ),
    ]
