# Generated by Django 6.1.2 on 2026-10-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_cpu_motherboard_alter_component_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboardspec',
            name='pcie_lanes',
            field=models.CharField(blank=True, help_text='e.g., 1x PCIe 5.0 x16, 2x PCIe 4.0 x4', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='motherboardspec',
            name='vrm_phases',
            field=models.CharField(blank=True, help_text='e.g., 16+2+2 Phases or 90A Power Stage', max_length=50, null=True),
        ),
    ]
